### PR TITLE
Implement GOntology class

### PR DESCRIPTION
**Pull request by mikpom**
During the discussion in #10 I suggested to implement a class for ontology. Here is the initial code for that. The docs and tests are fixed accordingly. 
The main idea is to make user access various tasks as methods of the GOntology instance. I used some quick and dirty workarounds in enrich.py but this seems to do the trick.

### CODE REVIEW

**Comment by jdrudolph** [comment]
Thanks a lot for the pull request and the work you put in it!

I would like to open two topics for discussion before I consider merging this pull request.
1. **Breaking backwards compatibility**: The changes that break existing code of all users will force them to either stay at the current version of `goenrich`, or update their code. This can be really painful. Could your suggested functionality, e.g. including `is_a` and `part_of` relationship be implemented without changing the API?
2. **Custom data representation**: I prefer data to speak for itself and utilize existing data representations, e.g. `networkx.DiGraph` and `pandas.DataFrame`. Users familiar with these packages are not required to learn any new classes, but can jump right into using `goenrich`. Why not use the node and edge attributes of the ontology graph to implement the same functionality, e.g. searching for terms by name?

I hope my comments are not discouraging, because while critical, I am very excited about improving the code!

**Comment by mikpom** [comment]
1. If backward compatibility is a major concern it is possible to retain versions of functions taking ontology graph as a first argument argument and versions implemented as `GOntology` methods. So all the previous code will work.  Of course relationship type can be done without classes. It is actually implemented in commit 84851ff and is a matter of ~5 lines of code.

2. The actual `nx.DiGraph` being read from the file is accessible as `O.graph` attribute and the user can always have lower level API if it is needed. But let's break down searching for terms example. Currently I just implemented the dummy version searching for exact names. One can imagine a lot of elaborations on that, e.g. to search by description of a term, to make fuzzy pattern search, to search by alternative IDs etc. All this definetely requires a separate function and not just filter hooks around `nx.DiGraph`. So possible solutions is to write functions taking ontology as a first argument or implement corresponding class methods. The latter is obviously more pythonic approach.
   
P.S. I also believe that since the trasition to OO model is done code becomes more maintainable and further changes are easier to implement. And a class is something Python user always expects. Doing so will make new users learn to use the package much faster.  Finally aside from all technicalities OOP is just cooler :-)

**Comment by jdrudolph** [comment]
Religious arguments about the merits of OOP aside, I think in this specific case the custom class does not provides functionality that would be painful to implement as a function operating directly on the `nx.DiGraph` of the ontology. Additionally it breaks the existing code for all users of the package, since the ontology is used in all subsequent analysis steps.

I would definitely merge the added functionality like searching by name, or filtering by different relations between terms, implemented in the same style as the rest of the package. Functions operating on standard data structures, mostly lists and dictionaries.

**Comment by mikpom** [comment]
Note about 'user expecting a class' is not a 'religious' comment it is just how I thought Python works.

Anyway I think that adding type of relationship ('is_a', 'part_of') is something very easy and important to do. Do you want me to make a pull request solely for this purpose? Also what about other relationships ('positively_regulates')?

**Comment by jdrudolph** [comment]
You can either add more commits to this pull request or open a new one. If you open another you can just close this one.

Regarding the relationships, feel free to add whichever ones you deem useful. I didn't explore these in detail.

**Pull request closed without merging**
