### PR TITLE
fix bug in calculate_pvalues

### PR DESCRIPTION
**Pull request by alexlenail**
See https://github.com/scipy/scipy/issues/7837

### CODE REVIEW

**Comment by alexlenail** [comment]
That second commit is because if there's actually 0 hits you want to pass `-1`, which I suppose is consistent...

**Comment by jdrudolph** [comment]
I just checked out your code on my machine and tests are failing as well. I guess this is actually a good thing, since your fix changes the calculation of all p-values. So this should be a matter of changing the assertion in the test...

**Comment by alexlenail** [comment]
@jdrudolph this is either floating-point issues or the reference has been updated, probably the latter. I think we should move away from testing using the actual GO reference and towards the solution you proposed in which we have a home-made reference graph.

**Comment by jdrudolph** [comment]
@zfrenchee I ran the test successfully just now on the `jdrudolph/goenrich:master` branch. Maybe first implement the tiny artificial test with the example you came up with. If we are confident that the p-value calculation is correct, we can modify the existing test so that it passes as well.

**Pull request merged**
